version: '3.8'

services:
  miner-api:
    build:
      context: .
      dockerfile: deval/api/dockerfile
    container_name: miner-api
    ports:
      - "8000:8000"
    environment:
      - MODEL_URL=${MODEL_URL}
    user: "miner"
    security_opt:
      - no-new-privileges  # Prevent privilege escalation
    cap_drop:
      - ALL  # Drop all unnecessary capabilities
    cap_add:
      - NET_BIND_SERVICE  # Allow binding to network services for internal comms
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

#  validator:
#    build:
#      context: .
#      dockerfile: dockerfile
#    volumes:
#      - /var/run/docker.sock:/var/run/docker.sock
#      - eval_llm:/app/eval_llm
#    networks:
#      - internal_net
#      - default
#    env_file:
#      - .env
#    command: >
#      poetry run python3 neurons/validator.py
#      --netuid ${NETUID:-15}
#      --wallet.name ${WALLET_NAME}
#      --wallet.hotkey ${HOTKEY}
#      --subtensor.network ${SUBTENSOR_NETWORK}


#networks:
#  internal_net:
#    driver: bridge
#    internal: true
